
# "bert-base-uncased", "bert-large-uncased", "bert-base-cased"
bert_model: "bert-base-cased"
lower: false
validation_data: "dev"
pretrained: null
topk: 500

preprocess_batch_size: 128
train_batch_size: 16
seed: 3435
cuda: -1
nosplit_parenth: false

lr: 5e-5
dropout: 0.1
grad_norm: 1
warmup_prop: 0.1
epochs: 10
log_interval: 100
save: null

max_num_neighbors: 50
random_neighbors_in_train: true
eval_num_neighbors: 100
eval_accuracy: false
pred_shard_size: 64
cosine: true

align_strategy: "first"  #"sum", "first", "last"

detach_db: false
subsample: 2500

# just_eval: null   # "dev", "dev-finetuned"
eval: false
zero_shot: false
